### ISSUE TITLE
'Conv2d' object has no attribute 'device'

### ISSUE THREAD

**Issue by LoiseauNicolas** [M3DV/ACSConv#14]
Hello, thank you to share your work. I wanted to try your program but i got an AttributeError.
```
from torchvision.models import resnet18
from acsconv.converters import ACSConverter
model_2d = resnet18(pretrained=True)
model_3d = ACSConverter(model_2d)
```
with this error : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-126-2824c693a04c>", line 1, in <module>
    model_3d = ACSConverter(model_2d)
  File "/home/loiseau/.local/lib/python3.9/site-packages/acsconv/converters/acsconv_converter.py", line 29, in __init__
    model = self.convert_module(model)
  File "/home/loiseau/.local/lib/python3.9/site-packages/acsconv/converters/base_converter.py", line 30, in convert_module
    kwargs = {k: getattr(child, k) for k in arguments}
  File "/home/loiseau/.local/lib/python3.9/site-packages/acsconv/converters/base_converter.py", line 30, in <dictcomp>
    kwargs = {k: getattr(child, k) for k in arguments}
  File "/home/loiseau/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'device'
```

**Comment by duducheng** [comment]
Hi @LoiseauNicolas ,

Can you please post you torch and torchvision version?

-------
Xiaoyang, can you have a look at this issue, maybe after the ICLR discussion ddl? @seanywang0408

**Comment by LoiseauNicolas** [comment]
Hi @duducheng, thank you for your quick answer.
I have 1.9.0 for torch and 0.10.0 for torchvision.

Ok i didn't get this on your readme "torch>=1.0.0 and torch<=1.8.0"
Sorry for this issue.

**Comment by duducheng** [comment]
Good to hear that!
